name: Kirim Analisis Telegram

on:
  schedule:
    # Menjalankan pada jam-jam strategis (07, 10, 13, 15, 18, 20, 23, 02 WIB)
    # Dikonversi ke UTC: 00, 03, 06, 08, 11, 13, 16, 19
    - cron: '0 0,3,6,8,11,13,16,19 * * *'
  workflow_dispatch:
    # Menambahkan tombol "Run workflow" di tab Actions
    # agar bisa dijalankan manual untuk tes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositori
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Jalankan Skrip Analisis
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
