# .github/workflows/scheduled_analysis.yml
name: Kirim Analisis Terjadwal

on:
  schedule:
    # Menjalankan pada jam 7 pagi, 1 siang, dan 8 malam WIB
    # Dikonversi ke UTC: 00:00, 06:00, 13:00
    - cron: '0 0,3,6,10,13,15 * * *'
  workflow_dispatch:
    # Menambahkan tombol "Run workflow" di tab Actions untuk tes manual

jobs:
  send-scheduled-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repositori
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Jalankan Skrip Analisis Terjadwal
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        CRYPTOCOMPARE_API_KEY: ${{ secrets.CRYPTOCOMPARE_API_KEY }}
      run: python scheduled_run.py
